// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy25CcvrOqheB9LCR_N-ChFnsBg8jbV4A',
    appId: '1:376252362790:web:f530312076c3df3cf0f6e7',
    messagingSenderId: '376252362790',
    projectId: 'help-corona-84f63',
    authDomain: 'help-corona-84f63.firebaseapp.com',
    databaseURL: 'https://help-corona-84f63.firebaseio.com',
    storageBucket: 'help-corona-84f63.appspot.com',
    measurementId: 'G-K13V83L4KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6eEB3MUq93kyQwZRwm-P4IbrhOOt-fQc',
    appId: '1:376252362790:android:2537334ae680911af0f6e7',
    messagingSenderId: '376252362790',
    projectId: 'help-corona-84f63',
    databaseURL: 'https://help-corona-84f63.firebaseio.com',
    storageBucket: 'help-corona-84f63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN7j5rgu6bcmd0f9F072JQqzX1fDAxRbM',
    appId: '1:376252362790:ios:a2183fd37cc21d16f0f6e7',
    messagingSenderId: '376252362790',
    projectId: 'help-corona-84f63',
    databaseURL: 'https://help-corona-84f63.firebaseio.com',
    storageBucket: 'help-corona-84f63.appspot.com',
    androidClientId: '376252362790-47okbb7rh558mqkntf9nuq4bdrs3le6l.apps.googleusercontent.com',
    iosClientId: '376252362790-9fntai3an732lllfj07us2897g6spqb5.apps.googleusercontent.com',
    iosBundleId: 'com.wcrop.cordes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN7j5rgu6bcmd0f9F072JQqzX1fDAxRbM',
    appId: '1:376252362790:ios:a2183fd37cc21d16f0f6e7',
    messagingSenderId: '376252362790',
    projectId: 'help-corona-84f63',
    databaseURL: 'https://help-corona-84f63.firebaseio.com',
    storageBucket: 'help-corona-84f63.appspot.com',
    androidClientId: '376252362790-47okbb7rh558mqkntf9nuq4bdrs3le6l.apps.googleusercontent.com',
    iosClientId: '376252362790-9fntai3an732lllfj07us2897g6spqb5.apps.googleusercontent.com',
    iosBundleId: 'com.wcrop.cordes',
  );
}
